[profile.default]
src = "node_modules/@luxfhe/foundry-mocks/src"
out = "out"
libs = ["lib", "node_modules"]

# Remappings for hardhat-foundry integration
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "@luxfhe/luxfhe-contracts/=node_modules/@luxfhe/contracts/",
    "@luxfhe/foundry-mocks/=node_modules/@luxfhe/foundry-mocks/"
]
